# Generated by Django 5.0.2 on 2024-03-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0004_alter_address_id_alter_apartment_id"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="apartment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apartments.apartment",
            ),
        ),
    ]
