# Generated by Django 5.0.2 on 2024-02-21 21:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=64, default="Poland")),
                ("street", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=64)),
                ("province", models.CharField(max_length=64)),
                ("postal_code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surface", models.DecimalField(decimal_places=2, default=Decimal("3.00"), max_digits=5, validators=[django.core.validators.MinValueValidator(3)])),
                ("price", models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1000)])),
                ("deposit", models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(50)])),
                ("is_available", models.BooleanField(default=True)),
                ("description", models.CharField(max_length=600)),
                ("is_furnished", models.BooleanField(default=True)),
                (
                    "address",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="apartments.Address"),
                ),
                (
                    "owner",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                (
                    "apartment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="apartments.Apartment"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
