# Generated by Django 5.0.2 on 2024-02-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(default="Poland", max_length=64),
        ),
    ]
