# Generated by Django 5.0.2 on 2024-02-20 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="deposit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(50)],
            ),
        ),
    ]
