# Generated by Django 5.0.2 on 2024-03-01 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("ALL", "Albanian Lek"),
                    ("EUR", "Euro"),
                    ("BYN", "Belarusian Ruble"),
                    ("BAM", "Bosnia and Herzegovina Convertible Mark"),
                    ("BGN", "Bulgarian Lev"),
                    ("HRK", "Croatian Kuna"),
                    ("CZK", "Czech Koruna"),
                    ("DKK", "Danish Krone"),
                    ("GBP", "British Pound Sterling"),
                    ("HUF", "Hungarian Forint"),
                    ("ISK", "Icelandic Króna"),
                    ("MDL", "Moldovan Leu"),
                    ("NOK", "Norwegian Krone"),
                    ("PLN", "Polish Złoty"),
                    ("RON", "Romanian Leu"),
                    ("RUB", "Russian Ruble"),
                    ("RSD", "Serbian Dinar"),
                    ("SEK", "Swedish Krona"),
                    ("CHF", "Swiss Franc"),
                    ("UAH", "Ukrainian Hryvnia"),
                ],
                default=1,
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                choices=[
                    ("Albania", "Albania"),
                    ("Andorra", "Andorra"),
                    ("Austria", "Austria"),
                    ("Belarus", "Belarus"),
                    ("Belgium", "Belgium"),
                    ("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
                    ("Bulgaria", "Bulgaria"),
                    ("Croatia", "Croatia"),
                    ("Cyprus", "Cyprus"),
                    ("Czech Republic", "Czech Republic"),
                    ("Denmark", "Denmark"),
                    ("Estonia", "Estonia"),
                    ("Finland", "Finland"),
                    ("France", "France"),
                    ("Germany", "Germany"),
                    ("Greece", "Greece"),
                    ("Hungary", "Hungary"),
                    ("Iceland", "Iceland"),
                    ("Ireland", "Ireland"),
                    ("Italy", "Italy"),
                    ("Kosovo", "Kosovo"),
                    ("Latvia", "Latvia"),
                    ("Liechtenstein", "Liechtenstein"),
                    ("Lithuania", "Lithuania"),
                    ("Luxembourg", "Luxembourg"),
                    ("Malta", "Malta"),
                    ("Moldova", "Moldova"),
                    ("Monaco", "Monaco"),
                    ("Montenegro", "Montenegro"),
                    ("Netherlands", "Netherlands"),
                    ("North Macedonia", "North Macedonia"),
                    ("Norway", "Norway"),
                    ("Poland", "Poland"),
                    ("Portugal", "Portugal"),
                    ("Romania", "Romania"),
                    ("Russia", "Russia"),
                    ("San Marino", "San Marino"),
                    ("Serbia", "Serbia"),
                    ("Slovakia", "Slovakia"),
                    ("Slovenia", "Slovenia"),
                    ("Spain", "Spain"),
                    ("Sweden", "Sweden"),
                    ("Switzerland", "Switzerland"),
                    ("Ukraine", "Ukraine"),
                    ("United Kingdom", "United Kingdom"),
                    ("Vatican City", "Vatican City"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="surface",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(3)],
            ),
        ),
    ]
