# Generated by Django 5.0.2 on 2024-02-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0002_alter_address_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=10),
        ),
    ]
