# Generated by Django 5.0.2 on 2024-02-21 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0002_alter_apartment_deposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="is_furnished",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="apartment",
            name="surface",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="deposit",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(50)],
            ),
        ),
    ]
