# Generated by Django 5.0.2 on 2024-03-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0002_apartment_currency_alter_address_country_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Visit",
        ),
    ]
