# Generated by Django 5.0.2 on 2024-02-21 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0003_apartment_is_furnished_apartment_surface_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="tenants",
        ),
        migrations.RenameField(
            model_name="visit",
            old_name="date",
            new_name="date_time",
        ),
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.CharField(default="Poland", max_length=64),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="is_furnished",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="surface",
            field=models.DecimalField(
                decimal_places=2,
                default=3,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(3)],
            ),
        ),
        migrations.DeleteModel(
            name="Preferences",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
