# Generated by Django 5.0.2 on 2024-02-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0004_remove_room_tenants_rename_date_visit_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=10),
        ),
    ]
