COUNTRY_CHOICES = (
    ("Albania", "Albania"),
    ("Andorra", "Andorra"),
    ("Austria", "Austria"),
    ("Belarus", "Belarus"),
    ("Belgium", "Belgium"),
    ("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
    ("Bulgaria", "Bulgaria"),
    ("Croatia", "Croatia"),
    ("Cyprus", "Cyprus"),
    ("Czech Republic", "Czech Republic"),
    ("Denmark", "Denmark"),
    ("Estonia", "Estonia"),
    ("Finland", "Finland"),
    ("France", "France"),
    ("Germany", "Germany"),
    ("Greece", "Greece"),
    ("Hungary", "Hungary"),
    ("Iceland", "Iceland"),
    ("Ireland", "Ireland"),
    ("Italy", "Italy"),
    ("Kosovo", "Kosovo"),
    ("Latvia", "Latvia"),
    ("Liechtenstein", "Liechtenstein"),
    ("Lithuania", "Lithuania"),
    ("Luxembourg", "Luxembourg"),
    ("Malta", "Malta"),
    ("Moldova", "Moldova"),
    ("Monaco", "Monaco"),
    ("Montenegro", "Montenegro"),
    ("Netherlands", "Netherlands"),
    ("North Macedonia", "North Macedonia"),
    ("Norway", "Norway"),
    ("Poland", "Poland"),
    ("Portugal", "Portugal"),
    ("Romania", "Romania"),
    ("Russia", "Russia"),
    ("San Marino", "San Marino"),
    ("Serbia", "Serbia"),
    ("Slovakia", "Slovakia"),
    ("Slovenia", "Slovenia"),
    ("Spain", "Spain"),
    ("Sweden", "Sweden"),
    ("Switzerland", "Switzerland"),
    ("Ukraine", "Ukraine"),
    ("United Kingdom", "United Kingdom"),
    ("Vatican City", "Vatican City"),
)

CURRENCY_CHOICES = (
    ("ALL", "Albanian Lek"),
    ("EUR", "Euro"),
    ("BYN", "Belarusian Ruble"),
    ("BAM", "Bosnia and Herzegovina Convertible Mark"),
    ("BGN", "Bulgarian Lev"),
    ("HRK", "Croatian Kuna"),
    ("CZK", "Czech Koruna"),
    ("DKK", "Danish Krone"),
    ("GBP", "British Pound Sterling"),
    ("HUF", "Hungarian Forint"),
    ("ISK", "Icelandic Króna"),
    ("MDL", "Moldovan Leu"),
    ("NOK", "Norwegian Krone"),
    ("PLN", "Polish Złoty"),
    ("RON", "Romanian Leu"),
    ("RUB", "Russian Ruble"),
    ("RSD", "Serbian Dinar"),
    ("SEK", "Swedish Krona"),
    ("CHF", "Swiss Franc"),
    ("UAH", "Ukrainian Hryvnia"),
)
