VISIT_STATES = (
    ("PENDING", "PENDING"),
    ("ACCEPTED", "ACCEPTED"),
    ("CANCELLED_BY_OWNER", "CANCELED_BY_OWNER"),
    ("CANCELED_BY_USER", "CANCELED_BY_USER"),
    ("CHANGE_REQUESTED", "CHANGE_REQUESTED"),
)
