# Generated by Django 5.0.2 on 2024-03-16 19:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apartments", "0004_alter_address_id_alter_apartment_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "png"]
                            )
                        ],
                    ),
                ),
                ("is_main", models.BooleanField(default=False)),
                (
                    "apartment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apartments.apartment",
                    ),
                ),
            ],
        ),
    ]
