# Generated by Django 5.0.2 on 2024-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentimage",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
